baseURL = "/"
languageCode = "en-us"
title = "Deductive"

# Theme Config
theme = "hugo-saasify-theme"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

# Enable taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Pagination
paginate = 6
paginatePath = "page"

[params]
  description = ""
  author = "Deductive"
  logo = "logo.png"
  
  # Global CTA Configuration
  [params.cta]
    enable = true
    title = "Klaar om uw bedrijf te transformeren met AI?"
    description = "Ontdek hoe onze AI-oplossingen uw organisatie kunnen versterken."
    gradient_from = "#4534da"  # Primary purple/blue
    gradient_to = "#08d5f9"    # Secondary light blue
    gradient_angle = 30
    [params.cta.primary_button]
      text = "Gratis Consultatie"
      url = "/contact"
    [params.cta.secondary_button]
      text = "Bekijk Oplossingen"
      url = "/oplossingen"
  
  # Footer Configuration
  [params.footer]
    column_1_title = "OPLOSSINGEN"
    column_2_title = "BEDRIJF"
    column_3_title = "JURIDISCH"
  
  # Social Media Configuration
  [params.social]
    discord = "#"
    linkedin = "#"
    instagram = "#"
  
  [params.header]
    # Header background and border styles (optional)
    background = "bg-gradient-to-r from-primary-100 to-secondary-100 backdrop-blur-sm"
    border = "border-b border-gray-200"
    
    # Logo configuration
    [params.header.logo]
      src = "/logo.png"
    
    # Menu configuration
    [params.header.menu]
      spacing = "space-x-8"
      
      # Dropdown menu configuration
      [params.header.menu.dropdown]
        width = "w-72"
        container_padding = "py-6"
        item_padding = "px-8 py-3"
        background = "bg-white"
        border = "border border-gray-100"
        shadow = "shadow-xl"
        radius = "rounded-lg"
        text_color = "text-gray-700"
        hover_background = "hover:bg-gray-50"
        text_size = "text-sm"
    
    # Button configuration
    [params.header.buttons]
      # Sign In button
      [params.header.buttons.signIn]
        text = "Klantportaal"
        url = "https://agentfrontend.onrender.com"
      
      # Get Started button
      [params.header.buttons.getStarted]
        text = "Contact"
        url = "/contact"

  # Blog configuration
  [params.blog]
    enable = true
    title = "Latest Articles"
    subtitle = "Learn more about web development and best practices"
    
    # Blog CTA configuration
    [params.blog.cta]
      enable = true  # Enable/disable CTA in blog posts
    
    # Sidebar configuration
    [params.blog.sidebar]
      # Recent articles section
      [params.blog.sidebar.recent]
        enable = true
        title = "Recent Articles"
        count = 5
      
      # Categories section
      [params.blog.sidebar.categories]
        enable = true
        title = "Categories"
      
      # Tags section
      [params.blog.sidebar.tags]
        enable = true
        title = "Popular Tags"
        count = 20

      # Subscribe form section
      [params.blog.sidebar.subscribe]
        enable = true
        title = "Subscribe to Newsletter"
        description = "Get the latest posts delivered right to your inbox"
        action = "https://formspree.io/f/your-form-id"
        emailName = "email"
        buttonText = "Subscribe"
        placeholder = "Enter your email"
        disclaimer = "We respect your privacy. Unsubscribe at any time."

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[build]
  writeStats = true

[build.buildStats]
  enable = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Navigation Menu
[menu]
  [[menu.main]]
    name = "Oplossingen"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "AI Chatbot", url = "/oplossingen/ai-chatbot/" },
        { name = "AI-Agents", url = "/oplossingen/ai-agents/" },
        { name = "Offertetool", url = "/oplossingen/offertetool/" }
      ]
  [[menu.main]]
    name = "Prijzen"
    url = "/pricing"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3
  [[menu.main]]
    name = "Bedrijf"
    weight = 4
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Over Ons", url = "/company/" },
        { name = "Vacatures", url = "/careers/" }
      ]

  # Footer Column 1 Menu
  [[menu.footer_column_1]]
    name = "AI Chatbot"
    url = "/oplossingen/ai-chatbot/"
    weight = 1
  [[menu.footer_column_1]]
    name = "AI-Agents"
    url = "/oplossingen/ai-agents/"
    weight = 2
  [[menu.footer_column_1]]
    name = "Offertetool"
    url = "/oplossingen/offertetool/"
    weight = 3

  # Footer Column 2 Menu
  [[menu.footer_column_2]]
    name = "Blog"
    url = "/blog"
    weight = 1
  [[menu.footer_column_2]]
    name = "Over Ons"
    url = "/company"
    weight = 2
  [[menu.footer_column_2]]
    name = "Vacatures"
    url = "/careers"
    weight = 3

  # Footer Column 3 Menu
  [[menu.footer_column_3]]
    name = "Licentie"
    url = "/license"
    weight = 1
  [[menu.footer_column_3]]
    name = "Privacybeleid"
    url = "/privacy"
    weight = 2
