baseURL = "https://deductiveai.github.io/deductivewebsite/"
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = false

# Multilingual Configuration
[languages]
  [languages.nl]
    languageCode = "nl-NL"
    languageName = "Nederlands"
    title = "Deductive"
    weight = 1
    contentDir = "content"
    [languages.nl.params]
      description = "AI-oplossingen die uw bedrijf vooruithelpen"
      keywords = "AI, kunstmatige intelligentie, chatbot, automatisering, Nederland"
      # Dutch specific parameters
      [languages.nl.params.cta]
        enable = true
        title = "Klaar om uw bedrijf te transformeren met AI?"
        description = "Ontdek hoe onze AI-oplossingen uw organisatie kunnen versterken."
        [languages.nl.params.cta.primary_button]
          text = "Plan een demo"
          url = "/deductivewebsite/contact"
        [languages.nl.params.cta.secondary_button]
          text = "Bekijk Oplossingen"
          url = "/deductivewebsite/oplossingen"
  
  [languages.en]
    languageCode = "en-US" 
    languageName = "English"
    title = "Deductive"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      description = "AI solutions that drive your business forward"
      keywords = "AI, artificial intelligence, chatbot, automation, Netherlands"
      # English specific parameters
      [languages.en.params.cta]
        enable = true
        title = "Ready to transform your business with AI?"
        description = "Discover how our AI solutions can strengthen your organization."
        [languages.en.params.cta.primary_button]
          text = "Schedule a demo"
          url = "/deductivewebsite/en/contact"
        [languages.en.params.cta.secondary_button]
          text = "View Solutions"
          url = "/deductivewebsite/en/solutions"

# Theme Config
theme = "hugo-saasify-theme"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

# Enable sitemap generation
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = false

# SEO and sitemap configuration
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Enable taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Pagination
paginate = 6
paginatePath = "page"

[params]
  description = ""
  author = "Deductive"
  logo = "logo.png"
  
  # Global CTA Configuration
  [params.cta]
    enable = true
    title = "Klaar om uw bedrijf te transformeren met AI?"
    description = "Ontdek hoe onze AI-oplossingen uw organisatie kunnen versterken."
    gradient_from = "#4534da"  # Primary purple/blue
    gradient_to = "#08d5f9"    # Secondary light blue
    gradient_angle = 30
    [params.cta.primary_button]
      text = "Plan een demo"
      url = "/deductivewebsite/contact"
    [params.cta.secondary_button]
      text = "Bekijk Oplossingen"
      url = "/deductivewebsite/oplossingen"
  
  # Footer Configuration
  [params.footer]
    column_1_title = "OPLOSSINGEN"
    column_2_title = "BEDRIJF"
    column_3_title = "JURIDISCH"
  
  # Social Media Configuration
  [params.social]
    discord = "https://discord.gg/deductive"
    linkedin = "https://linkedin.com/company/deductive"
    instagram = "https://instagram.com/deductive"
    github = "https://github.com/deductive"
  
  [params.header]
    # Header background and border styles (optional)
    background = "bg-gray-900"
    border = "border-b border-gray-800"
    
    # Logo configuration
    [params.header.logo]
      src = "logo.png"
    
    # Menu configuration
    [params.header.menu]
      spacing = "space-x-8"
      
      # Dropdown menu configuration
      [params.header.menu.dropdown]
        width = "w-72"
        container_padding = "py-6"
        background = "bg-gray-800"
        border = "border border-gray-700"
        text_color = "text-gray-200"
        hover_background = "hover:bg-gray-700"
        item_padding = "px-8 py-3"
        shadow = "shadow-xl"
        radius = "rounded-lg"
        text_size = "text-sm"
    
    # Button configuration
    [params.header.buttons]
      # Sign In button
      [params.header.buttons.signIn]
        text = "Klantportaal"
        url = "https://agentfrontend.onrender.com"
      
      # Get Started button
      [params.header.buttons.getStarted]
        text = "Contact"
        url = "/deductivewebsite/contact"

  # Blog configuration
  [params.blog]
    enable = true
    title = "Latest Articles"
    subtitle = "Learn more about web development and best practices"
    
    # Blog CTA configuration
    [params.blog.cta]
      enable = true  # Enable/disable CTA in blog posts
    
    # Sidebar configuration
    [params.blog.sidebar]
      # Recent articles section
      [params.blog.sidebar.recent]
        enable = true
        title = "Recent Articles"
        count = 5
      
      # Categories section
      [params.blog.sidebar.categories]
        enable = true
        title = "Categories"
      
      # Tags section
      [params.blog.sidebar.tags]
        enable = true
        title = "Popular Tags"
        count = 20

      # Subscribe form section
      [params.blog.sidebar.subscribe]
        enable = true
        title = "Subscribe to Newsletter"
        description = "Get the latest posts delivered right to your inbox"
        action = "https://formspree.io/f/your-form-id"
        emailName = "email"
        buttonText = "Subscribe"
        placeholder = "Enter your email"
        disclaimer = "We respect your privacy. Unsubscribe at any time."

# Module configuration removed - using traditional theme approach

[build]
  writeStats = true

[build.buildStats]
  enable = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Dutch Navigation Menu
[languages.nl.menu]
  [[languages.nl.menu.main]]
    name = "Oplossingen"
    weight = 1
    [languages.nl.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "AI Chatbot", url = "/deductivewebsite/oplossingen/ai-chatbot/" },
        { name = "AI-Agents", url = "/deductivewebsite/oplossingen/ai-agents/" },
        { name = "Offertetool", url = "/deductivewebsite/oplossingen/offertetool/" }
      ]
  # [[languages.nl.menu.main]]
  #   name = "Prijzen"
  #   url = "/pricing"
  #   weight = 2
  [[languages.nl.menu.main]]
    name = "Blog"
    url = "/deductivewebsite/blog"
    weight = 3
  [[languages.nl.menu.main]]
    name = "Bedrijf"
    weight = 4
    [languages.nl.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Over Ons", url = "/deductivewebsite/company/" },
        { name = "Vacatures", url = "/deductivewebsite/careers/" }
      ]

# English Navigation Menu
[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Solutions"
    weight = 1
    [languages.en.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "AI Chatbot", url = "/deductivewebsite/en/solutions/ai-chatbot/" },
        { name = "AI Agents", url = "/deductivewebsite/en/solutions/ai-agents/" },
        { name = "Quote Tool", url = "/deductivewebsite/en/solutions/quote-tool/" }
      ]
  # [[languages.en.menu.main]]
  #   name = "Pricing"
  #   url = "/en/pricing"
  #   weight = 2
  [[languages.en.menu.main]]
    name = "Blog"
    url = "/deductivewebsite/en/blog"
    weight = 3
  [[languages.en.menu.main]]
    name = "Company"
    weight = 4
    [languages.en.menu.main.params]
      has_submenu = true
      submenu = [
        { name = "About Us", url = "/deductivewebsite/en/company/" },
        { name = "Careers", url = "/deductivewebsite/en/careers/" }
      ]

# Footer Menus (Global)
[[menu.footer_column_1]]
  name = "AI Chatbot"
  url = "/deductivewebsite/oplossingen/ai-chatbot/"
  weight = 1
[[menu.footer_column_1]]
  name = "AI-Agents"
  url = "/deductivewebsite/oplossingen/ai-agents/"
  weight = 2
[[menu.footer_column_1]]
  name = "Offertetool"
  url = "/deductivewebsite/oplossingen/offertetool/"
  weight = 3

[[menu.footer_column_2]]
  name = "Blog"
  url = "/deductivewebsite/blog"
  weight = 1
[[menu.footer_column_2]]
  name = "Over Ons"
  url = "/deductivewebsite/company"
  weight = 2
[[menu.footer_column_2]]
  name = "Vacatures"
  url = "/deductivewebsite/careers"
  weight = 3
[[menu.footer_column_2]]
  name = "Sitemap"
  url = "/deductivewebsite/nl/sitemap.xml"
  weight = 4

[[menu.footer_column_3]]
  name = "Privacybeleid"
  url = "/deductivewebsite/privacy"
  weight = 1
[[menu.footer_column_3]]
  name = "Algemene Voorwaarden"
  url = "/deductivewebsite/terms"
  weight = 2
[[menu.footer_column_3]]
  name = "Cookies"
  url = "/deductivewebsite/cookies"
  weight = 3
